mtc/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import DetailView
from mtc.membership.models import Member, Parish, FamilyMember

#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from mtc.settings import DEBUG

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mtc.views.home', name='home'),
    # url(r'^mtc/', include('mtc.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^tiny_mce/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/sa-user/workspace/mtc/staticfiles/jscripts/tiny_mce'}),
    (r'^css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/sa-user/workspace/mtc/staticfiles/css'}),
    (r'^search/$', 'mtc.search.views.search'),
    (r'^members/directory/$', 'mtc.membership.views.directoryview'),
    (r'^members/directory/dirpdf/$', 'mtc.membership.views.render_to_pdf2'),
 #(r'^members/(?P<pk>\d+)/directory/$', DetailView.as_view(model=Members, context_object_name="members_list")),
    (r'', include('django.contrib.flatpages.urls')),
)



#urlpatterns += staticfiles_urlpatterns()

mtc/membership/models.py
from django.db import models
from django.db.models import Count

class Parish(models.Model):
    name=models.CharField(max_length=100, blank = True)
    address_line1 = models.CharField("Address line 1", max_length = 45, blank = True)
    address_line2 = models.CharField("Address line 2", max_length = 45, blank = True)
    city = models.CharField("City", max_length = 50, blank = True)
    state_province = models.CharField("State/Province", max_length = 40, blank = True)
#    member_id = models.ForeignKey(Members)

    def __unicode__(self):
        return self.name+" "+self.address_line1+" "+self.address_line2+" "+self.city
    
# Create your models here.
class Member(models.Model):
    last_name = models.CharField("Last name", max_length=50, blank = False)
    first_name = models.CharField("First name", max_length=50, blank = False)
    middle_name = models.CharField("Middle name", max_length=50, blank = True)
    dob = models.DateField("Date of birth", blank = True, null = True)
    cell = models.CharField("Cell", max_length=20, blank = True)
    phone = models.CharField("Phone", max_length=20, blank = True)
    email = models.EmailField("Email", blank = True)
    address_line1 = models.CharField("Address line 1", max_length = 45, blank = True)
    address_line2 = models.CharField("Address line 2", max_length = 45, blank = True)
    city = models.CharField("City", max_length = 50, blank = True)
    postal_code = models.CharField("ZIP/Postal code", max_length = 10, blank = True)
    state_province = models.CharField("State/Province", max_length = 40, blank = True)
    country = models.CharField("Country", max_length = 40, blank = True)
    prayer_group_code = models.CharField("Area Prayer Group Number", max_length=10, blank = True)
    house_name=models.CharField("House name", max_length=50, blank=True)
    parish_id = models.ForeignKey(Parish)
    

    class meta:
        ordering = ['last_name']
        
    def get_fulladdress(self):
        return self.address_line1 +" "+self.address_line2 +" "+ self.city+" "+self.postal_code+" "+self.state_province
    get_fulladdress.short_description = 'Address'
    
    #===========================================================================
    # def get_familycount(self):
    #    membersfamily.member_count = self.objects.annotate(family_count=Count(''))
    #===========================================================================
        
    def __unicode__(self):
        return self.last_name+" "+self.first_name+" "+self.middle_name
  

class FamilyMember(models.Model):
    relationship_choices = (
        (u'C', u'Child'),
        (u'P', u'Parent'),
        (u'S', u'Spouse'),
        (u'B', u'Sibling'),
        
    )
    last_name = models.CharField("Last name", max_length=50, blank = True)
    first_name = models.CharField("First name", max_length=50, blank = True)
    middle_name = models.CharField("Middle name", max_length=50, blank = True)
    dob = models.DateField("Date of birth", blank = True, null = True)
    email = models.EmailField("Email", blank = True)
    relationship = models.CharField(max_length=1, choices=relationship_choices)
    member_id = models.ForeignKey(Member)

    def __unicode__(self):
        return self.last_name+" "+self.first_name+" "+self.middle_name
        

mtc/membership/views.py
from mtc.membership.models import Member, Parish, FamilyMember
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template.loader import render_to_string
from django.template import RequestContext
from reportlab.pdfgen import canvas
import cStringIO as StringIO
import ho.pisa as pisa
from django.template.loader import get_template
from django.template import Context
from cgi import escape
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


    # resp = render_to_response('membership/member_directory.html', {'memberdetails': paginate(request, Member.objects.order_by('last_name'))})
    #---------------------------------------------- result = StringIO.StringIO()
    #------------------------------------------ pdf=pisa.CreatePDF(html, result)
    #----------------------------------------------------------- if not pdf.err:
        #---- return HttpResponse(result.getvalue(), mimetype='application/pdf')
    #----- return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))

def render_to_pdf3(request):
    template = get_template('membership/member_directory.html')
    context = Context({'pagesize':'A4', 'memberdetails': Member.objects.all().order_by('last_name'), })
    html  = template.render(context)
    return HttpResponse(html)
    result = StringIO.StringIO()
    pdf=pisa.CreatePDF(html, result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), mimetype='application/pdf')
    return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))

def render_to_pdf(template_src, context_dict):
    #template = get_template(template_src)
    #context=Context(context_dict)
    #html=template.render(context)
    html=render_to_response(template_src, context_dict)
    result=StringIO.StringIO()
    pdf=pisa.pisaDocument(StringIO.StringIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), mimetype='application/pdf')
    return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))


def directoryview_pdf(request):
    return render_to_pdf('membership/member_directory.html',{'pagesize':'A4', 'memberdetails': paginate(request, Member.objects.all().order_by('last_name'))})
    #return render_to_response('membership/member_directory.html', {'memberdetails': memberdetails})
    
def paginate(request, modelobj):
    paginator = Paginator(modelobj, 100)
    page = request.GET.get('page', 1)
    try:
        details = paginator.page(page)
    except PageNotAnInteger:
        details = paginator.page(1)
    except EmptyPage:
        details = paginator.page(paginator.num_pages)
    return details

def render_to_pdf2(request):
    html = render_to_response('membership/member_directory.html', {'memberdetails': paginate(request, Member.objects.order_by('last_name'))})
    
    response = HttpResponse()
    response['Content-Type'] ='application/pdf'
    response['Content-Disposition']='attachment; filename=%s.pdf'%('blah')
    
    pisa.CreatePDF(
    src=html,
    dest=response,
    show_error_as_pdf=True)
    
    #response.flush()
    return response         
    
def directoryview(request):
    #memberdetails = Members.objects.all().order_by('last_name')
    return render_to_response('membership/member_directory.html', {'memberdetails': paginate(request, Member.objects.order_by('last_name'))})
    #return render_to_response('membership/member_directory.html', {'memberdetails': Member.objects.all()})

mtc/templates/membership/member_directory.html
<!doctype html>
<head>
  <meta charset="utf-8">
      <meta name="viewport" content="width=device-width,initial-scale=1">

     <style type="text/css">
     html { font-size: 100%; overflow-y: scroll; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
body {
margin: 0;
background-color: #fff;
font: 11px/20px "Helvetica Neue",Helvetica,Arial,sans-serif;
line-height: 1.231;
}
body, button, input, select, textarea { font: 11px/20px "Helvetica Neue",Helvetica,Arial,sans-serif; color: #000; letter-spacing:1px;
} 
/* =============================================================================
Tables
========================================================================== */
table { border-collapse: collapse; border-spacing: 0; width: 75%; border: 0px solid black; }
td, tr { vertical-align: top; border: 0px}
#membername
{
	width: 35%;
	font-weight:bold;	
}
#dob
{
	width: 5%;
}
#email
{
	width: 25%;
}
#address
{
	width: 35%;	
}
     
     </style>
    <title>St. Andrews Mar Thomas Church</title>
</head>
	

<body>    
	{% for member in memberdetails.object_list %}
	<table>
			<tr>
				<td id="membername">{{ member.last_name }}&nbsp;{{ member.first_name }}&nbsp;{{ member.middle_name }}</td>
				{% if member.dob == None %}
					<td id="dob"></td>
				{% else %}
					<td id="dob">{{ member.dob|date:"j-M" }}</td>
				{% endif %}
				<td id="email">{{ member.email }}</td>
				<td id="address" rowspan="0">
					{{ member.address_line1 }}<br>
					{{ member.address_line2 }}<br>
					{{ member.city }}<br>
					{{ member.state_province }}<br>
					{{ member.postal_code }}<br>
					Phone: {{ member.phone }}<br>
					Cell: {{ member.cell }}
				</td>
				</td>
			</tr>
			{% for familymember in member.familymember_set.all %}
			<tr>
				<td>{{ familymember.first_name }}&nbsp;{{ familymember.middle_name }}&nbsp;{{ familymember.last_name }}</td>
				<td>{{ familymember.dob|date:"j-M" }}</td>
				<td>{{ familymember.email }}</td>
			</tr>
			{% endfor %}
			<tr>
				<td colspan="3">Parish: {{ member.parish_id }}</td>
			</tr>	
			<tr>
				<td>APGC&nbsp;&nbsp;&nbsp;{{ member.prayer_group_code }}</td>	
			</tr>
			<tr>
				{% if member.house_name == None %}
					<td id="housename">House Name: </td>
				{% else %}
					<td>House Name: {{ member.house_name }}</td>
				{% endif %}
			</tr>
			<br/>
</table>
	{% endfor %}

</body>

</html>

mtc/templates/membership/members_list.html
{% extends "membership/base.html" %}

{% block content %}
    <h2>Members</h2>
    <ul>
        {% for members in members_list %}
            <li>{{ members.last_name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

class Parish(models.Model):
    name
    address_line1 
    address_line2 
    city 
    state_province 

class Members(models.Model):
    last_name
    first_name
    middle_name 
    dob 
    cell
    phone
    email
    address_line1 
    address_line2 
    city 
    postal_code 
    state_province 
    country 
    prayer_group_code 
    parish_id 



class MembersFamily(models.Model):

    last_name 
    first_name 
    middle_name
    dob 
    email 
    relationship 
    member_id 

mtc/templates/membership/paginate.html
<div class="pagination">
    <span class="step-links">
        {% if memberdetails.has_previous %}
            <a href="?page={{ memberdetails.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ memberdetails.number }}<!--  of {{ memberdetails.paginator.num_pages }}. -->
        </span>
        
        {% if memberdetails.has_next %}
            <a href="?page={{ memberdetails.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>